package kernel

import (
	"fmt"
	"time"
)

// ChargeType defines the pricing and recurring model for a service subscription.
type ChargeType string

const (
	ChargeTypeMetered          ChargeType = "metered"           // Pay-as-you-go consumption
	ChargeTypeRecurringMonthly ChargeType = "recurring_monthly" // Fixed monthly subscription
	ChargeTypeRecurringYearly  ChargeType = "recurring_yearly"  // Fixed yearly subscription
	ChargeTypeOneTime          ChargeType = "one_time"          // One-time addon / setup fee
)

// ServiceSubscription defines a tenant's subscription contract for a specific service.
// Each service subscription maintains its own AnchorTime, Timezone, and ChargeType.
type ServiceSubscription struct {
	SubscriptionID string     `json:"subscription_id"` // Unique subscription identifier
	TenantKey      string     `json:"tenant_key"`      // Customer/API key identifier
	ServiceID      string     `json:"service_id"`      // e.g. "ai-completion", "storage", "service1"
	PlanID         string     `json:"plan_id"`         // e.g. "pro-plan", "starter-plan"
	ChargeType     ChargeType `json:"charge_type"`     // metered, recurring_monthly, recurring_yearly
	Timezone       string     `json:"timezone"`        // IANA Timezone, e.g. "America/New_York", "UTC"
	AnchorTime     time.Time  `json:"anchor_time"`     // Service subscription start timestamp
	Status         string     `json:"status"`          // "active", "cancelled", "past_due"
}

// CurrentCycleWindow calculates the exact UTC cycle bounds [startUTC, endUTC)
// for this service subscription based on its AnchorTime, Timezone, and ChargeType.
func (s ServiceSubscription) CurrentCycleWindow(at time.Time) (startUTC, endUTC time.Time) {
	if at.Before(s.AnchorTime) {
		return s.AnchorTime, s.AnchorTime
	}

	loc, err := time.LoadLocation(s.Timezone)
	if err != nil {
		loc = time.UTC
	}

	anchorLocal := s.AnchorTime.In(loc)
	atLocal := at.In(loc)

	switch s.ChargeType {
	case ChargeTypeRecurringYearly:
		years := atLocal.Year() - anchorLocal.Year()
		startLocal := anchorLocal.AddDate(years, 0, 0)
		if startLocal.After(atLocal) {
			startLocal = anchorLocal.AddDate(years-1, 0, 0)
		}
		endLocal := startLocal.AddDate(1, 0, 0)
		return startLocal.UTC(), endLocal.UTC()

	case ChargeTypeRecurringMonthly, ChargeTypeMetered:
		fallthrough
	default:
		yearDiff := atLocal.Year() - anchorLocal.Year()
		monthDiff := int(atLocal.Month()) - int(anchorLocal.Month())
		totalMonths := yearDiff*12 + monthDiff

		startLocal := anchorLocal.AddDate(0, totalMonths, 0)
		if startLocal.After(atLocal) {
			startLocal = anchorLocal.AddDate(0, totalMonths-1, 0)
		}
		endLocal := startLocal.AddDate(0, 1, 0)
		return startLocal.UTC(), endLocal.UTC()
	}
}

// MeteringEvent represents an atomic billable event generated by any service.
type MeteringEvent struct {
	EventID   string                 `json:"event_id"`   // Idempotency / event identifier
	TenantKey string                 `json:"tenant_key"`  // Customer/API key identifier
	ServiceID string                 `json:"service_id"`  // Service originating the event
	MetricID  string                 `json:"metric_id"`   // Metric name (e.g. "tokens", "requests")
	Unit      string                 `json:"unit"`        // Unit of measurement (e.g. "count", "bytes")
	Quantity  int64                  `json:"quantity"`    // Quantity consumed
	Timestamp time.Time              `json:"timestamp"`   // UTC timestamp of event occurrence
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
}

// MetricSummary holds aggregated consumption totals for a single metric within a service cycle.
type MetricSummary struct {
	MetricID    string `json:"metric_id"`    // Metric identifier
	Unit        string `json:"unit"`         // Unit of measurement
	CycleTotal  int64  `json:"cycle_total"`  // Total quantity consumed within cycle window
	TotalEvents int64  `json:"total_events"` // Number of metering events recorded
}

// ServiceBillingStatement represents the statement for a single service subscription.
type ServiceBillingStatement struct {
	SubscriptionID string                    `json:"subscription_id"`
	TenantKey      string                    `json:"tenant_key"`
	ServiceID      string                    `json:"service_id"`
	PlanID         string                    `json:"plan_id"`
	ChargeType     ChargeType                `json:"charge_type"`
	Timezone       string                    `json:"timezone"`
	CycleStartUTC  time.Time                 `json:"cycle_start_utc"`
	CycleEndUTC    time.Time                 `json:"cycle_end_utc"`
	Metrics        map[string]*MetricSummary `json:"metrics"`
	GeneratedAt    time.Time                 `json:"generated_at"`
}

// TenantBillingOverview consolidates all service billing statements for a tenant.
type TenantBillingOverview struct {
	TenantKey         string                    `json:"tenant_key"`
	SubscriptionState string                    `json:"subscription_state"`
	Statements        []ServiceBillingStatement `json:"statements"`
	GeneratedAt       time.Time                 `json:"generated_at"`
}

// Validate validates that a MeteringEvent has required fields.
func (e *MeteringEvent) Validate() error {
	if e.TenantKey == "" {
		return fmt.Errorf("tenant_key is required")
	}
	if e.ServiceID == "" {
		return fmt.Errorf("service_id is required")
	}
	if e.MetricID == "" {
		return fmt.Errorf("metric_id is required")
	}
	if e.Quantity <= 0 {
		return fmt.Errorf("quantity must be greater than 0")
	}
	return nil
}
